name: StorringtonDramatics
favicon: null
layout_spectrum: 0.29430177179165184
typography_spectrum: 0.27746970392763615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7897098974790424
  lightness: 0.4280701354146004
  saturation: 0.32059788168407977
  rhythmicContrast: 0.30424280161969364
purpose: []
